#ifndef KANON_VERSION_H__
#define KANON_VERSION_H__

#define KANON_VER_MAJOR 1
#define KANON_VER_MINOR 7
#define KANON_VER_PATCH 5

#define KANON_VERSION (KANON_VER_MAJOR * 10000 + KANON_VER_MINOR * 100 + KANON_VER_PATCH)

#endif
